### ISSUE TITLE
Custom plural symbols?

### ISSUE THREAD

**Issue by jackfirth** [greghendershott/flexpr#1]
When turning a `flexpr` into an `xexpr`, it would be nice if I provide my own `plural-symbol?` and `plural-symbol->singular-symbol` functions to let me deal with things like a "Wolves" key where I want child elements to have the tag name "Wolf". Keyword arguments or a separate function would be great.

**Comment by greghendershott** [comment]
Good point!

After a bit of thought, I decided to make this a parameter, whose value is a function that does double duty as a predicate and a conversion function.

**Comment by greghendershott** [comment]
Well [this failure on Racket HEAD](https://travis-ci.org/greghendershott/flexpr/builds/86746060) is interesting. It looks like the hash table implementation has recently changed. My tests depend on an order that is not guaranteed. I'll need to fix that.

So I have to make you for making this feature request, because it caused me to re-run the tests against HEAD and notice this. :)

**Comment by jackfirth** [comment]
Fantastic! The feature, not the bug. Though I am glad this revealed the bug :)

**Comment by greghendershott** [comment]
@jackfirth I left a comment on #2 and would welcome your input. (I'm not sure if GitHub will notify you even though I @ mentioned you there, because you're not active on that issue (yet)).
