### ISSUE TITLE
`write-flexpr-xml/content` doesn't allow specifying the root element

### ISSUE THREAD

**Issue by jackfirth** [greghendershott/flexpr#6]
`write-flexpr-xml/content` is a useful shortcut, but it doesn't allow specifying the root element like `flexpr->xexpr` does. I'd like to be able to do this:

``` racket
(write-flexpr-xml/content (hasheq 'foo 1 'bar 2) #:root 'BRAAAAAAINS)
```

**Comment by jackfirth** [comment]
(Note: I have a patch for this, but won't be able to submit it as a PR for a day or two)

**Comment by greghendershott** [comment]
That was a silly mistake. I'd originally defined this as a simple `compose`, which did handle this for `flexpr->xml`. Then I remembered the optional `out` arg for `write-xml/content`, stopped using `compose` ... and in the process forgot about `flexpr->xexpr`. Sigh.

Does your patch fix the same issue with `display-flexpr-xml/content`?

If still convenient for you to make the PR in a day or two, I'm happy to take that. Otherwise let me know and I'll fix myself. Either way -- thanks!

**Comment by jackfirth** [comment]
My new job is quite stringent about software licensing, so in order for me to submit the patch I'd have to add "Google Inc." to the list of copyright holders in the project license. If that's alright with you I'll open a PR, but otherwise I'll leave it up to you.

**Comment by greghendershott** [comment]
Although I'm not necessarily opposed to that, I think in this case it's simpler for me to make the change, which I just pushed. Thanks again for reporting this!
